services:
  db:
    image: postgres:15
    container_name: match-db
    restart: always
    environment:
      POSTGRES_DB: matchdb
      POSTGRES_USER: matchuser
      POSTGRES_PASSWORD: matchpass123
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matchuser -d matchdb"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - match_pgdata:/var/lib/postgresql/data
    networks:
      - internal_network

  redis:
    image: redis:7-alpine
    container_name: match-redis
    restart: always
    networks:
      - internal_network


  web:
    build: .
    container_name: match-web
    restart: always
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn match.wsgi:application --bind 0.0.0.0:8001 --workers 1 --timeout 120"
    volumes:
      - .:/app
      - match_static_volume:/app/static
      - match_media_volume:/app/media
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: match.settings
      POSTGRES_DB: matchdb
      POSTGRES_USER: matchuser
      POSTGRES_PASSWORD: matchpass123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      TELEGRAM_BOT_API_KEY: "8084516709:AAFZiSWDBm_raXMqUEpDqF4_GrOgqvgxe64"  # ✅ Added
      #DJANGO_SECRET_KEY: "your-production-secret-key-here"  # ✅ Added

    networks:
      - internal_network
      - nginx-proxy-net

  bot:
    build: .
    container_name: match-bot
    restart: always
    command: python manage.py runbot
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: match.settings
      POSTGRES_DB: matchdb
      POSTGRES_USER: matchuser
      POSTGRES_PASSWORD: matchpass123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - internal_network

  worker:
    build: .
    container_name: match-worker
    restart: always
    command: celery -A match worker -l info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - redis
      - web
    environment:
      DJANGO_SETTINGS_MODULE: match.settings
      POSTGRES_DB: matchdb
      POSTGRES_USER: matchuser
      POSTGRES_PASSWORD: matchpass123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
  nginx-proxy-net:
    external: true

volumes:
  match_pgdata:
  match_static_volume:
  match_media_volume: